import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es";

const translations = {
  en: {
    // ── Nav / AppShell ─────────────────────────────────────────────────────
    home: "Home",
    howItWorks: "How It Works",
    pricing: "Pricing",
    faq: "FAQ",
    findShifts: "Find Shifts",
    postJob: "Post a Job",
    signIn: "Sign in",
    signOut: "Sign out",
    profile: "Profile",
    earnings: "Earnings",
    applications: "Applications",
    ratings: "Ratings",
    availability: "Availability",
    history: "History",
    live: "Live",
    jobs: "Jobs",
    notifications: "Notifications",
    clearAll: "Clear all",
    allCaughtUp: "You're all caught up",
    switchToSpanish: "Cambiar a Español",
    switchToEnglish: "Switch to English",

    // ── Feed ───────────────────────────────────────────────────────────────
    liveShifts: "Live Shifts",
    availableWorkers: "Available Workers",
    noShiftsFound: "No shifts found",
    noWorkersFound: "No workers found",
    applyNow: "Apply Now",
    hireNow: "Hire Now",
    perHour: "/hr",
    verified: "Verified",
    permanent: "Permanent Potential",
    viewDetails: "View Details",
    filterByCity: "Filter by city",
    filterByRole: "Filter by role",
    allRoles: "All Roles",
    searchPlaceholder: "Search shifts, roles...",
    loadingFeed: "Loading shifts...",
    refreshing: "Refreshing...",
    postedBy: "Posted by",
    hiresFor: "Hiring for",
    shiftEnds: "Shift ends",
    minRatingRequired: "Min rating",
    openToHire: "Open to hire",

    // ── Job Detail ─────────────────────────────────────────────────────────
    jobDetails: "Job Details",
    shiftTime: "Shift Time",
    payRate: "Pay Rate",
    location: "Location",
    description: "Description",
    requirements: "Requirements",
    minRating: "Min Rating",
    applyForShift: "Apply for This Shift",
    coverNote: "Cover Note",
    coverNotePlaceholder: "Tell the employer why you're the right fit...",
    bankInfo: "Bank Account Info",
    routingNumber: "Routing Number",
    accountNumber: "Account Number",
    submitApplication: "Submit Application",
    applicationSubmitted: "Application Submitted!",
    signInToApply: "Sign In to Apply",
    verifyToApply: "Verify ID to Apply",
    applied: "Applied!",
    ratingTooLow: "Rating Too Low",
    applyEarn: "Apply · Earn",
    shiftExpired: "Shift Expired",
    shiftFilled: "Shift Filled",
    restaurantName: "Restaurant",
    city: "City",
    hours: "Hours",
    totalPay: "Total Pay",
    workerPayout: "Your Payout (90%)",
    verificationPending: "Verification under review — you can still apply. Shift confirms once approved.",
    verifyRequired: "Verify your identity to apply for shifts and receive payments.",
    verifyNow: "Verify Now",
    shiftDetails: "Shift Details",
    payBreakdown: "Pay Breakdown",
    platformFeeNote: "Platform keeps 10%, you keep 90%",

    // ── Post Job ───────────────────────────────────────────────────────────
    postAJob: "Post a Shift",
    postAShift: "Post a Shift",
    chooseAPlan: "Choose a plan to get started",
    fillShiftDetails: "Fill in your shift details",
    roleNeeded: "Role Needed",
    hourlyRate: "Hourly Rate ($/hr)",
    startDate: "Start Date",
    startTime: "Start Time",
    endTime: "End Time",
    jobDescription: "Job Description",
    descriptionPlaceholder: "Describe the shift, duties, dress code...",
    minimumRating: "Minimum Worker Rating",
    permanentOpportunity: "Permanent Opportunity",
    permanentDesc: "This shift may lead to a full-time position",
    postShift: "Post Shift",
    posting: "Posting...",
    restaurantNameLabel: "Restaurant / Venue Name",
    restaurantNamePlaceholder: "e.g. Uchi Austin",
    locationLabel: "Address / Location",
    locationPlaceholder: "123 Main St, Austin TX",
    selectCityFilter: "Select City",
    payPreview: "Pay Preview",
    estimatedHours: "Est. Hours",
    totalCost: "Total Cost (you pay)",
    workerReceives: "Worker Receives",
    shiftIsLive: "Shift is live in the feed!",
    fillAllFields: "Please fill in all required fields",
    invalidTime: "Invalid date/time — end must be after start",
    couponCode: "Have a Coupon Code?",
    couponPlaceholder: "SHIFT-XXXXXXXX",
    applyCoupon: "Apply",
    couponApplied: "Coupon applied! Credits added.",
    creditsAvailable: "Credits available",
    firstPostFree: "Your first post is FREE",
    firstPostFreeDesc: "No charge — post your first shift on us",
    unlimitedPosts: "Unlimited posts (subscription active)",
    postsRemaining: "post(s) remaining",
    choosePlan: "Choose a Plan",
    singlePost: "Single Post",
    singlePostDesc: "Post one shift to the live feed",
    bundlePost: "3-Post Bundle",
    bundlePostDesc: "Best value for occasional hiring",
    monthlyUnlimited: "Monthly Unlimited",
    monthlyUnlimitedDesc: "For restaurants that hire regularly",
    continue: "Continue",
    back: "Back",
    noRatingReq: "No Requirement",

    // ── Applications ───────────────────────────────────────────────────────
    myApplications: "My Applications",
    myShifts: "My Shifts",
    applicants: "Applicants",
    noApplications: "No applications yet",
    noApplicants: "No applicants yet",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    completed: "Completed",
    hired: "Hired",
    accept: "Accept",
    reject: "Reject",
    acceptAndPay: "Accept & Pay Escrow",
    viewProfile: "View Profile",
    shiftStatus: "Shift Status",
    payEscrow: "Pay Escrow",
    releasePayment: "Release Payment",
    paymentHeld: "Payment Held",
    paymentReleased: "Payment Released",
    rateWorker: "Rate Worker",
    rateEmployer: "Rate Employer",
    alreadyRated: "Rated",
    workerHired: "You're Hired!",
    workerHiredDesc: "Congrats! Show up 10 min early and bring your best.",
    clockIn: "Clock In",
    clockOut: "Clock Out",
    clockedIn: "Clocked In",
    clockedOut: "Clocked Out",
    shiftStarted: "Shift Started",
    shiftEnded: "Shift Ended",
    autoReleaseNote: "Payment auto-releases 24h after clock-out",
    escrowNote: "Funds held securely until shift completes",
    workerProfile: "Worker Profile",
    employerView: "Employer View",
    workerView: "Worker View",
    noShiftsYet: "No shifts yet",
    postFirstShift: "Post your first shift",
    applyToShifts: "Browse and apply to shifts",

    // ── Earnings ───────────────────────────────────────────────────────────
    myEarnings: "My Earnings",
    availableBalance: "Available Balance",
    pendingBalance: "Pending",
    totalEarned: "Total Earned",
    withdraw: "Withdraw",
    connectStripe: "Connect Bank Account",
    paymentHistory: "Payment History",
    noEarnings: "No earnings yet",
    platformFee: "Platform Fee (10%)",
    yourPayout: "Your Payout (90%)",
    connectBankDesc: "Connect your bank account to receive payouts",
    stripeConnected: "Bank Connected",
    stripeConnectedDesc: "Your bank account is connected",
    payoutSent: "Payout sent!",
    withdrawFunds: "Withdraw Funds",
    instantPayout: "Instant Payout",
    standardPayout: "Standard (2-3 days)",
    earningsBreakdown: "Earnings Breakdown",
    shiftDate: "Shift Date",
    amount: "Amount",
    fee: "Fee",
    net: "Net",
    status: "Status",
    released: "Released",
    held: "Held",
    totalShifts: "Total Shifts",
    avgPerShift: "Avg Per Shift",

    // ── Profile ────────────────────────────────────────────────────────────
    myProfile: "My Profile",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    name: "Name",
    bio: "Bio",
    bioPlaceholder: "Tell employers about your experience...",
    skills: "Skills",
    experience: "Experience",
    experiencePlaceholder: "Years of experience, past restaurants...",
    profileImage: "Profile Image URL",
    workerType: "I am a",
    worker: "Worker",
    employer: "Employer",
    switchRole: "Switch Role",
    memberSince: "Member since",
    shiftsCompleted: "Shifts Completed",
    avgRating: "Avg Rating",
    reliabilityScore: "Reliability Score",
    publicProfile: "Public Profile",
    contactPreference: "Contact Preference",
    phone: "Phone",
    email: "Email",
    bankDetails: "Bank Details",
    routingNumberLabel: "Routing Number",
    accountNumberLabel: "Account Number",
    saveProfile: "Save Profile",
    profileSaved: "Profile saved!",
    selectSkills: "Select your skills",
    selectCityProfile: "Select your city",
    noRatingYet: "No rating yet",
    verifiedBadge: "ID Verified",
    contractSigned: "Contract Signed",

    // ── Ratings ────────────────────────────────────────────────────────────
    myRatings: "My Ratings",
    ratingsReceived: "Received",
    ratingsGiven: "Given",
    noRatings: "No ratings yet",
    overallRating: "Overall Rating",
    totalRatings: "Total Ratings",
    ratingBreakdown: "Rating Breakdown",
    recentReviews: "Recent Reviews",
    respondToReview: "Respond",
    yourResponse: "Your Response",
    submitResponse: "Submit Response",
    responseSaved: "Response saved!",
    ratingLabels: ["Absolutely", "Sure", "Maybe", "Not really", "Never"],

    // ── Rate Shift ─────────────────────────────────────────────────────────
    rateShift: "Rate This Shift",
    rateWorkerTitle: "Rate the Worker",
    rateEmployerTitle: "Rate the Employer",
    ratingQuestion: "Would you work with this person again?",
    ratingComment: "Add a comment (optional)",
    ratingCommentPlaceholder: "Share your experience...",
    submitRating: "Submit Rating",
    ratingSubmitted: "Rating submitted!",
    ratingAlreadySubmitted: "You've already rated this shift",

    // ── Worker Availability ────────────────────────────────────────────────
    myAvailability: "My Availability",
    postAvailability: "Post Availability",
    availableNow: "Available Now",
    availableFrom: "Available From",
    availableTo: "Available To",
    preferredRoles: "Preferred Roles",
    preferredCity: "Preferred City",
    hourlyExpectation: "Hourly Rate Expectation",
    availabilityNote: "Note",
    availabilityNotePlaceholder: "Any additional info for employers...",
    postAvailabilityBtn: "Post My Availability",
    availabilityPosted: "Availability posted!",
    deleteAvailability: "Delete",
    availabilityDeleted: "Availability removed",
    myPosts: "My Posts",
    noAvailabilityPosts: "No availability posts yet",
    addAvailability: "Add Availability",

    // ── Worker Verification ────────────────────────────────────────────────
    verifyIdentity: "Verify Your Identity",
    verificationStatus: "Verification Status",
    notVerified: "Not Verified",
    verificationPendingStatus: "Under Review",
    verificationApproved: "Verified",
    verificationRejected: "Rejected",
    uploadId: "Upload ID Photo",
    idPhotoUrl: "ID Photo URL",
    idPhotoUrlPlaceholder: "Paste a link to your government ID photo",
    submitVerification: "Submit for Verification",
    verificationSubmitted: "Verification submitted! We'll review within 24 hours.",
    verificationBenefits: "Verified workers get more shifts and higher pay",
    whyVerify: "Why verify?",
    verifyBenefit1: "Get hired faster — employers prefer verified workers",
    verifyBenefit2: "Higher pay rates on premium shifts",
    verifyBenefit3: "Access to exclusive restaurant partners",
    verifyBenefit4: "Verified badge on your profile",

    // ── Contract Agreement ─────────────────────────────────────────────────
    contractTitle: "Independent Contractor Agreement",
    contractSubtitle: "1099 Contractor Terms",
    contractIntro: "Please read and sign the agreement below to start working shifts on ShiftChef.",
    signatureLabel: "Your Signature",
    signaturePlaceholder: "Draw or type your signature",
    typedSignature: "Type your name",
    typedSignaturePlaceholder: "Full legal name",
    signContract: "I Agree & Sign",
    contractSigned_msg: "Contract signed! You're ready to work.",
    alreadySigned: "You've already signed the agreement",
    scrollToSign: "Scroll to bottom to sign",
    clearSignature: "Clear",

    // ── Onboarding ─────────────────────────────────────────────────────────
    welcome: "Welcome to ShiftChef",
    iAmA: "I am a...",
    lookingForWork: "Worker",
    lookingForWork_desc: "I want to find shifts and get paid fast",
    hiringStaff: "Employer",
    hiringStaff_desc: "I need to hire hospitality staff quickly",
    getStarted: "Get Started",
    workerGiveaway: "$100 Amazon Gift Card Giveaway",
    workerGiveawayDesc: "Sign up as a worker and complete your first shift to enter",
    employerPromo: "First Post FREE",
    employerPromoDesc: "New employers get their first shift post at no charge",

    // ── Employer Dashboard ─────────────────────────────────────────────────
    employerDashboard: "Employer Dashboard",
    totalSpent: "Total Spent",
    shiftsCompleted_emp: "Shifts Completed",
    workersHired: "Workers Hired",
    avgCostPerShift: "Avg Cost / Shift",
    preferredWorkers: "Preferred Workers",
    preferredWorkersDesc: "Workers you've hired 2+ times",
    shiftHistory: "Shift History",
    noShiftHistory: "No completed shifts yet",
    rehire: "Re-hire",
    workerRating: "Your Rating",
    amountPaid: "Amount Paid",

    // ── Common ─────────────────────────────────────────────────────────────
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    close: "Close",
    search: "Search",
    filter: "Filter",
    noResults: "No results found",
    required: "Required",
    optional: "Optional",
    submit: "Submit",
    success: "Success!",
    comingSoon: "Coming soon",
    role: "Role",
    selectRole: "Select a role",
    cook: "Cook",
    sous_chef: "Sous Chef",
    prep: "Prep Cook",
    dishwasher: "Dishwasher",
    cleaner: "Cleaner",
    server: "Server",
    bartender: "Bartender",
    host: "Host",
    manager: "Manager",
    stars: "stars",
    perHr: "/hr",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "days ago",
  },

  es: {
    // ── Nav / AppShell ─────────────────────────────────────────────────────
    home: "Inicio",
    howItWorks: "Cómo Funciona",
    pricing: "Precios",
    faq: "Preguntas Frecuentes",
    findShifts: "Buscar Turnos",
    postJob: "Publicar Trabajo",
    signIn: "Iniciar Sesión",
    signOut: "Cerrar Sesión",
    profile: "Perfil",
    earnings: "Ganancias",
    applications: "Solicitudes",
    ratings: "Calificaciones",
    availability: "Disponibilidad",
    history: "Historial",
    live: "En Vivo",
    jobs: "Trabajos",
    notifications: "Notificaciones",
    clearAll: "Limpiar todo",
    allCaughtUp: "Todo al día",
    switchToSpanish: "Cambiar a Español",
    switchToEnglish: "Switch to English",

    // ── Feed ───────────────────────────────────────────────────────────────
    liveShifts: "Turnos Disponibles",
    availableWorkers: "Trabajadores Disponibles",
    noShiftsFound: "No se encontraron turnos",
    noWorkersFound: "No se encontraron trabajadores",
    applyNow: "Aplicar Ahora",
    hireNow: "Contratar Ahora",
    perHour: "/hr",
    verified: "Verificado",
    permanent: "Potencial Permanente",
    viewDetails: "Ver Detalles",
    filterByCity: "Filtrar por ciudad",
    filterByRole: "Filtrar por rol",
    allRoles: "Todos los Roles",
    searchPlaceholder: "Buscar turnos, roles...",
    loadingFeed: "Cargando turnos...",
    refreshing: "Actualizando...",
    postedBy: "Publicado por",
    hiresFor: "Contratando para",
    shiftEnds: "Turno termina",
    minRatingRequired: "Calificación mínima",
    openToHire: "Disponible para contratar",

    // ── Job Detail ─────────────────────────────────────────────────────────
    jobDetails: "Detalles del Turno",
    shiftTime: "Horario del Turno",
    payRate: "Tarifa de Pago",
    location: "Ubicación",
    description: "Descripción",
    requirements: "Requisitos",
    minRating: "Calificación Mínima",
    applyForShift: "Aplicar a Este Turno",
    coverNote: "Nota de Presentación",
    coverNotePlaceholder: "Cuéntale al empleador por qué eres la persona indicada...",
    bankInfo: "Información Bancaria",
    routingNumber: "Número de Ruta",
    accountNumber: "Número de Cuenta",
    submitApplication: "Enviar Solicitud",
    applicationSubmitted: "¡Solicitud Enviada!",
    signInToApply: "Iniciar Sesión para Aplicar",
    verifyToApply: "Verificar ID para Aplicar",
    applied: "¡Aplicado!",
    ratingTooLow: "Calificación Muy Baja",
    applyEarn: "Aplicar · Ganar",
    shiftExpired: "Turno Expirado",
    shiftFilled: "Turno Cubierto",
    restaurantName: "Restaurante",
    city: "Ciudad",
    hours: "Horas",
    totalPay: "Pago Total",
    workerPayout: "Tu Pago (90%)",
    verificationPending: "Verificación en revisión — aún puedes aplicar. El turno se confirma una vez aprobado.",
    verifyRequired: "Verifica tu identidad para aplicar a turnos y recibir pagos.",
    verifyNow: "Verificar Ahora",
    shiftDetails: "Detalles del Turno",
    payBreakdown: "Desglose de Pago",
    platformFeeNote: "La plataforma retiene 10%, tú recibes 90%",

    // ── Post Job ───────────────────────────────────────────────────────────
    postAJob: "Publicar un Turno",
    postAShift: "Publicar un Turno",
    chooseAPlan: "Elige un plan para comenzar",
    fillShiftDetails: "Completa los detalles del turno",
    roleNeeded: "Rol Necesario",
    hourlyRate: "Tarifa por Hora ($/hr)",
    startDate: "Fecha de Inicio",
    startTime: "Hora de Inicio",
    endTime: "Hora de Fin",
    jobDescription: "Descripción del Trabajo",
    descriptionPlaceholder: "Describe el turno, tareas, código de vestimenta...",
    minimumRating: "Calificación Mínima del Trabajador",
    permanentOpportunity: "Oportunidad Permanente",
    permanentDesc: "Este turno puede convertirse en un puesto de tiempo completo",
    postShift: "Publicar Turno",
    posting: "Publicando...",
    restaurantNameLabel: "Nombre del Restaurante / Local",
    restaurantNamePlaceholder: "ej. Uchi Austin",
    locationLabel: "Dirección / Ubicación",
    locationPlaceholder: "123 Calle Principal, Austin TX",
    selectCityFilter: "Seleccionar Ciudad",
    payPreview: "Vista Previa del Pago",
    estimatedHours: "Horas Est.",
    totalCost: "Costo Total (pagas tú)",
    workerReceives: "El Trabajador Recibe",
    shiftIsLive: "¡El turno está en vivo en el feed!",
    fillAllFields: "Por favor completa todos los campos requeridos",
    invalidTime: "Fecha/hora inválida — la hora de fin debe ser después del inicio",
    couponCode: "¿Tienes un Código de Cupón?",
    couponPlaceholder: "SHIFT-XXXXXXXX",
    applyCoupon: "Aplicar",
    couponApplied: "¡Cupón aplicado! Créditos agregados.",
    creditsAvailable: "Créditos disponibles",
    firstPostFree: "Tu primera publicación es GRATIS",
    firstPostFreeDesc: "Sin costo — publica tu primer turno gratis",
    unlimitedPosts: "Publicaciones ilimitadas (suscripción activa)",
    postsRemaining: "publicación(es) restante(s)",
    choosePlan: "Elige un Plan",
    singlePost: "Publicación Individual",
    singlePostDesc: "Publica un turno en el feed en vivo",
    bundlePost: "Paquete de 3 Publicaciones",
    bundlePostDesc: "Mejor valor para contrataciones ocasionales",
    monthlyUnlimited: "Ilimitado Mensual",
    monthlyUnlimitedDesc: "Para restaurantes que contratan regularmente",
    continue: "Continuar",
    back: "Atrás",
    noRatingReq: "Sin Requisito",

    // ── Applications ───────────────────────────────────────────────────────
    myApplications: "Mis Solicitudes",
    myShifts: "Mis Turnos",
    applicants: "Solicitantes",
    noApplications: "Sin solicitudes aún",
    noApplicants: "Sin solicitantes aún",
    pending: "Pendiente",
    accepted: "Aceptado",
    rejected: "Rechazado",
    completed: "Completado",
    hired: "Contratado",
    accept: "Aceptar",
    reject: "Rechazar",
    acceptAndPay: "Aceptar y Pagar Depósito",
    viewProfile: "Ver Perfil",
    shiftStatus: "Estado del Turno",
    payEscrow: "Pagar Depósito",
    releasePayment: "Liberar Pago",
    paymentHeld: "Pago Retenido",
    paymentReleased: "Pago Liberado",
    rateWorker: "Calificar Trabajador",
    rateEmployer: "Calificar Empleador",
    alreadyRated: "Calificado",
    workerHired: "¡Estás Contratado!",
    workerHiredDesc: "¡Felicidades! Llega 10 min antes y da lo mejor de ti.",
    clockIn: "Registrar Entrada",
    clockOut: "Registrar Salida",
    clockedIn: "Entrada Registrada",
    clockedOut: "Salida Registrada",
    shiftStarted: "Turno Iniciado",
    shiftEnded: "Turno Finalizado",
    autoReleaseNote: "El pago se libera automáticamente 24h después de la salida",
    escrowNote: "Fondos retenidos de forma segura hasta que el turno se complete",
    workerProfile: "Perfil del Trabajador",
    employerView: "Vista del Empleador",
    workerView: "Vista del Trabajador",
    noShiftsYet: "Sin turnos aún",
    postFirstShift: "Publica tu primer turno",
    applyToShifts: "Explora y aplica a turnos",

    // ── Earnings ───────────────────────────────────────────────────────────
    myEarnings: "Mis Ganancias",
    availableBalance: "Saldo Disponible",
    pendingBalance: "Pendiente",
    totalEarned: "Total Ganado",
    withdraw: "Retirar",
    connectStripe: "Conectar Cuenta Bancaria",
    paymentHistory: "Historial de Pagos",
    noEarnings: "Sin ganancias aún",
    platformFee: "Comisión de Plataforma (10%)",
    yourPayout: "Tu Pago (90%)",
    connectBankDesc: "Conecta tu cuenta bancaria para recibir pagos",
    stripeConnected: "Banco Conectado",
    stripeConnectedDesc: "Tu cuenta bancaria está conectada",
    payoutSent: "¡Pago enviado!",
    withdrawFunds: "Retirar Fondos",
    instantPayout: "Pago Instantáneo",
    standardPayout: "Estándar (2-3 días)",
    earningsBreakdown: "Desglose de Ganancias",
    shiftDate: "Fecha del Turno",
    amount: "Monto",
    fee: "Comisión",
    net: "Neto",
    status: "Estado",
    released: "Liberado",
    held: "Retenido",
    totalShifts: "Total de Turnos",
    avgPerShift: "Promedio por Turno",

    // ── Profile ────────────────────────────────────────────────────────────
    myProfile: "Mi Perfil",
    editProfile: "Editar Perfil",
    saveChanges: "Guardar Cambios",
    name: "Nombre",
    bio: "Biografía",
    bioPlaceholder: "Cuéntale a los empleadores sobre tu experiencia...",
    skills: "Habilidades",
    experience: "Experiencia",
    experiencePlaceholder: "Años de experiencia, restaurantes anteriores...",
    profileImage: "URL de Foto de Perfil",
    workerType: "Soy",
    worker: "Trabajador",
    employer: "Empleador",
    switchRole: "Cambiar Rol",
    memberSince: "Miembro desde",
    shiftsCompleted: "Turnos Completados",
    avgRating: "Calificación Promedio",
    reliabilityScore: "Puntuación de Confiabilidad",
    publicProfile: "Perfil Público",
    contactPreference: "Preferencia de Contacto",
    phone: "Teléfono",
    email: "Correo Electrónico",
    bankDetails: "Datos Bancarios",
    routingNumberLabel: "Número de Ruta",
    accountNumberLabel: "Número de Cuenta",
    saveProfile: "Guardar Perfil",
    profileSaved: "¡Perfil guardado!",
    selectSkills: "Selecciona tus habilidades",
    selectCityProfile: "Selecciona tu ciudad",
    noRatingYet: "Sin calificación aún",
    verifiedBadge: "ID Verificado",
    contractSigned: "Contrato Firmado",

    // ── Ratings ────────────────────────────────────────────────────────────
    myRatings: "Mis Calificaciones",
    ratingsReceived: "Recibidas",
    ratingsGiven: "Dadas",
    noRatings: "Sin calificaciones aún",
    overallRating: "Calificación General",
    totalRatings: "Total de Calificaciones",
    ratingBreakdown: "Desglose de Calificaciones",
    recentReviews: "Reseñas Recientes",
    respondToReview: "Responder",
    yourResponse: "Tu Respuesta",
    submitResponse: "Enviar Respuesta",
    responseSaved: "¡Respuesta guardada!",
    ratingLabels: ["Absolutamente", "Claro", "Tal vez", "No realmente", "Nunca"],

    // ── Rate Shift ─────────────────────────────────────────────────────────
    rateShift: "Calificar Este Turno",
    rateWorkerTitle: "Calificar al Trabajador",
    rateEmployerTitle: "Calificar al Empleador",
    ratingQuestion: "¿Trabajarías con esta persona de nuevo?",
    ratingComment: "Agrega un comentario (opcional)",
    ratingCommentPlaceholder: "Comparte tu experiencia...",
    submitRating: "Enviar Calificación",
    ratingSubmitted: "¡Calificación enviada!",
    ratingAlreadySubmitted: "Ya calificaste este turno",

    // ── Worker Availability ────────────────────────────────────────────────
    myAvailability: "Mi Disponibilidad",
    postAvailability: "Publicar Disponibilidad",
    availableNow: "Disponible Ahora",
    availableFrom: "Disponible Desde",
    availableTo: "Disponible Hasta",
    preferredRoles: "Roles Preferidos",
    preferredCity: "Ciudad Preferida",
    hourlyExpectation: "Expectativa de Tarifa por Hora",
    availabilityNote: "Nota",
    availabilityNotePlaceholder: "Información adicional para los empleadores...",
    postAvailabilityBtn: "Publicar Mi Disponibilidad",
    availabilityPosted: "¡Disponibilidad publicada!",
    deleteAvailability: "Eliminar",
    availabilityDeleted: "Disponibilidad eliminada",
    myPosts: "Mis Publicaciones",
    noAvailabilityPosts: "Sin publicaciones de disponibilidad aún",
    addAvailability: "Agregar Disponibilidad",

    // ── Worker Verification ────────────────────────────────────────────────
    verifyIdentity: "Verificar Tu Identidad",
    verificationStatus: "Estado de Verificación",
    notVerified: "No Verificado",
    verificationPendingStatus: "En Revisión",
    verificationApproved: "Verificado",
    verificationRejected: "Rechazado",
    uploadId: "Subir Foto de ID",
    idPhotoUrl: "URL de Foto de ID",
    idPhotoUrlPlaceholder: "Pega un enlace a la foto de tu identificación oficial",
    submitVerification: "Enviar para Verificación",
    verificationSubmitted: "¡Verificación enviada! Revisaremos en 24 horas.",
    verificationBenefits: "Los trabajadores verificados obtienen más turnos y mejor pago",
    whyVerify: "¿Por qué verificar?",
    verifyBenefit1: "Contratación más rápida — los empleadores prefieren trabajadores verificados",
    verifyBenefit2: "Mejores tarifas en turnos premium",
    verifyBenefit3: "Acceso a socios restauranteros exclusivos",
    verifyBenefit4: "Insignia de verificado en tu perfil",

    // ── Contract Agreement ─────────────────────────────────────────────────
    contractTitle: "Acuerdo de Contratista Independiente",
    contractSubtitle: "Términos de Contratista 1099",
    contractIntro: "Por favor lee y firma el acuerdo a continuación para comenzar a trabajar turnos en ShiftChef.",
    signatureLabel: "Tu Firma",
    signaturePlaceholder: "Dibuja o escribe tu firma",
    typedSignature: "Escribe tu nombre",
    typedSignaturePlaceholder: "Nombre legal completo",
    signContract: "Acepto y Firmo",
    contractSigned_msg: "¡Contrato firmado! Estás listo para trabajar.",
    alreadySigned: "Ya firmaste el acuerdo",
    scrollToSign: "Desplázate hasta abajo para firmar",
    clearSignature: "Limpiar",

    // ── Onboarding ─────────────────────────────────────────────────────────
    welcome: "Bienvenido a ShiftChef",
    iAmA: "Soy...",
    lookingForWork: "Trabajador",
    lookingForWork_desc: "Quiero encontrar turnos y cobrar rápido",
    hiringStaff: "Empleador",
    hiringStaff_desc: "Necesito contratar personal de hospitalidad rápidamente",
    getStarted: "Comenzar",
    workerGiveaway: "Sorteo de $100 en Amazon",
    workerGiveawayDesc: "Regístrate como trabajador y completa tu primer turno para participar",
    employerPromo: "Primera Publicación GRATIS",
    employerPromoDesc: "Los nuevos empleadores publican su primer turno sin costo",

    // ── Employer Dashboard ─────────────────────────────────────────────────
    employerDashboard: "Panel del Empleador",
    totalSpent: "Total Gastado",
    shiftsCompleted_emp: "Turnos Completados",
    workersHired: "Trabajadores Contratados",
    avgCostPerShift: "Costo Promedio / Turno",
    preferredWorkers: "Trabajadores Preferidos",
    preferredWorkersDesc: "Trabajadores que has contratado 2+ veces",
    shiftHistory: "Historial de Turnos",
    noShiftHistory: "Sin turnos completados aún",
    rehire: "Volver a Contratar",
    workerRating: "Tu Calificación",
    amountPaid: "Monto Pagado",

    // ── Common ─────────────────────────────────────────────────────────────
    loading: "Cargando...",
    error: "Algo salió mal",
    retry: "Intentar de Nuevo",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    confirm: "Confirmar",
    close: "Cerrar",
    search: "Buscar",
    filter: "Filtrar",
    noResults: "No se encontraron resultados",
    required: "Requerido",
    optional: "Opcional",
    submit: "Enviar",
    success: "¡Éxito!",
    comingSoon: "Próximamente",
    role: "Rol",
    selectRole: "Selecciona un rol",
    cook: "Cocinero",
    sous_chef: "Sous Chef",
    prep: "Cocinero de Preparación",
    dishwasher: "Lavaplatos",
    cleaner: "Limpiador",
    server: "Mesero",
    bartender: "Bartender",
    host: "Anfitrión",
    manager: "Gerente",
    stars: "estrellas",
    perHr: "/hr",
    today: "Hoy",
    yesterday: "Ayer",
    daysAgo: "días atrás",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isSpanish: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      return (localStorage.getItem("shiftchef_lang") as Language) || "en";
    } catch {
      return "en";
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("shiftchef_lang", lang);
    } catch {}
  };

  const t = (key: TranslationKey): string => {
    const val = translations[language][key];
    if (Array.isArray(val)) return (val as string[]).join(", ");
    return (val as string) || (translations.en[key] as string) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isSpanish: language === "es" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
